### ISSUE TITLE
Request for assistance with dataset access

### ISSUE THREAD

**Issue by lifrary** [bytedance/coconut_cvpr2024#1]
Hello,

I hope this message finds you well. I wanted to express my appreciation for your work on the dataset. 

I've encountered some issues while trying to access the data. The annotation download link (huggingface) seems to be inactive, and there might be a problem with the dataset on [Kaggle](https://www.kaggle.com/datasets/xueqingdeng/coconut?resource=download). 

If you could check on this when you have a moment, it would be very helpful. 

Thanks in advance for your help.

Best,

**Comment by WangYZ1608** [comment]
+1

**Comment by WangYZ1608** [comment]
> Hello,
> 
> I hope this message finds you well. I wanted to express my appreciation for your work on the dataset.
> 
> I've encountered some issues while trying to access the data. The annotation download link (huggingface) seems to be inactive, and there might be a problem with the dataset on [Kaggle](https://www.kaggle.com/datasets/xueqingdeng/coconut?resource=download).
> 
> If you could check on this when you have a moment, it would be very helpful.
> 
> Thanks in advance for your help.
> 
> Best,

+1

**Comment by lifrary** [comment]
> > Hello,
> > I hope this message finds you well. I wanted to express my appreciation for your work on the dataset.
> > I've encountered some issues while trying to access the data. The annotation download link (huggingface) seems to be inactive, and there might be a problem with the dataset on [Kaggle](https://www.kaggle.com/datasets/xueqingdeng/coconut?resource=download).
> > If you could check on this when you have a moment, it would be very helpful.
> > Thanks in advance for your help.
> > Best,
> 
> I just retry to download the dataset from kaggle, on my side there is no problem downloading. Could you please provide more details of the errors you encountered?
> 
> To download the dataset correctly, you should press the download button on the top right shown in the screenshot below to ensure you download the whole dataset. ![image](https://private-user-images.githubusercontent.com/43100519/324059694-a11d9a0c-cd7b-4037-8274-36a72c40ad50.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3NTExNzIsIm5iZiI6MTcxMzc1MDg3MiwicGF0aCI6Ii80MzEwMDUxOS8zMjQwNTk2OTQtYTExZDlhMGMtY2Q3Yi00MDM3LTgyNzQtMzZhNzJjNDBhZDUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDAxNTQzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5NTRmZjJhZDQ5NTUwZGYxM2I4MWZmOWUxMjE2ZGZlNGQ0YWExNWJiZWUxZDE0NTE0NzU5YTc2M2E3YTk4NTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AaQqz9S1IZU-Cyxuoqmm5X--WDm8RSpdMCmwmmGFxXE)

Hello, I am able to download the dataset from Kaggle without any issues. However, when I open the data:

- All the images appear as black images.
- The annotation count for coconut_b is only 117,378.

Could you please check if there is a problem with these aspects? Thank you!

**Comment by xdeng7** [comment]
> > > Hello,
> > > I hope this message finds you well. I wanted to express my appreciation for your work on the dataset.
> > > I've encountered some issues while trying to access the data. The annotation download link (huggingface) seems to be inactive, and there might be a problem with the dataset on [Kaggle](https://www.kaggle.com/datasets/xueqingdeng/coconut?resource=download).
> > > If you could check on this when you have a moment, it would be very helpful.
> > > Thanks in advance for your help.
> > > Best,
> > 
> > 
> > I just retry to download the dataset from kaggle, on my side there is no problem downloading. Could you please provide more details of the errors you encountered?
> > To download the dataset correctly, you should press the download button on the top right shown in the screenshot below to ensure you download the whole dataset. ![image](https://private-user-images.githubusercontent.com/43100519/324059694-a11d9a0c-cd7b-4037-8274-36a72c40ad50.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3NTExNzIsIm5iZiI6MTcxMzc1MDg3MiwicGF0aCI6Ii80MzEwMDUxOS8zMjQwNTk2OTQtYTExZDlhMGMtY2Q3Yi00MDM3LTgyNzQtMzZhNzJjNDBhZDUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDAxNTQzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5NTRmZjJhZDQ5NTUwZGYxM2I4MWZmOWUxMjE2ZGZlNGQ0YWExNWJiZWUxZDE0NTE0NzU5YTc2M2E3YTk4NTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AaQqz9S1IZU-Cyxuoqmm5X--WDm8RSpdMCmwmmGFxXE)
> 
> Hello, I am able to download the dataset from Kaggle without any issues. However, when I open the data:
> 
> * All the images appear as black images.
> * The annotation count for coconut_b is only 117,378.
> 
> Could you please check if there is a problem with these aspects? Thank you!

Thanks for checking the data.
1) for the black images, they area panoptic masks with discrete continuous numbers required panopticapi for visualization.
2) the split size for coconut-b, is actually the the extra split size substract coconut-s, so I will update the script to merge the provided coconut-b and coconut-s to build the ready-to-use coconut-b. The other option will be directly upload the ready-to-use version. Sorry about that, I am working on this.

**Comment by lifrary** [comment]
> > > > Hello,
> > > > I hope this message finds you well. I wanted to express my appreciation for your work on the dataset.
> > > > I've encountered some issues while trying to access the data. The annotation download link (huggingface) seems to be inactive, and there might be a problem with the dataset on [Kaggle](https://www.kaggle.com/datasets/xueqingdeng/coconut?resource=download).
> > > > If you could check on this when you have a moment, it would be very helpful.
> > > > Thanks in advance for your help.
> > > > Best,
> > > 
> > > 
> > > I just retry to download the dataset from kaggle, on my side there is no problem downloading. Could you please provide more details of the errors you encountered?
> > > To download the dataset correctly, you should press the download button on the top right shown in the screenshot below to ensure you download the whole dataset. ![image](https://private-user-images.githubusercontent.com/43100519/324059694-a11d9a0c-cd7b-4037-8274-36a72c40ad50.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3NTExNzIsIm5iZiI6MTcxMzc1MDg3MiwicGF0aCI6Ii80MzEwMDUxOS8zMjQwNTk2OTQtYTExZDlhMGMtY2Q3Yi00MDM3LTgyNzQtMzZhNzJjNDBhZDUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDAxNTQzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5NTRmZjJhZDQ5NTUwZGYxM2I4MWZmOWUxMjE2ZGZlNGQ0YWExNWJiZWUxZDE0NTE0NzU5YTc2M2E3YTk4NTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AaQqz9S1IZU-Cyxuoqmm5X--WDm8RSpdMCmwmmGFxXE)
> > 
> > 
> > Hello, I am able to download the dataset from Kaggle without any issues. However, when I open the data:
> > 
> > * All the images appear as black images.
> > * The annotation count for coconut_b is only 117,378.
> > 
> > Could you please check if there is a problem with these aspects? Thank you!
> 
> Thanks for checking the data.
> 
> 1. for the black images, they are panoptic masks with discrete continuous numbers required panopticapi for visualization.
> 2. the split size for coconut-b, is actually the the extra split size subtract coconut-s, so I will update the script to merge the provided coconut-b and coconut-s to build the ready-to-use coconut-b in the paper. The other option will be directly upload the ready-to-use version. Sorry about that, I am working on this.

Thank you for your prompt response. 
All of my questions have been answered, so I will close this issue. 
Once again, thank you for creating the dataset.

**Comment by xdeng7** [comment]
> > > > > Hello,
> > > > > I hope this message finds you well. I wanted to express my appreciation for your work on the dataset.
> > > > > I've encountered some issues while trying to access the data. The annotation download link (huggingface) seems to be inactive, and there might be a problem with the dataset on [Kaggle](https://www.kaggle.com/datasets/xueqingdeng/coconut?resource=download).
> > > > > If you could check on this when you have a moment, it would be very helpful.
> > > > > Thanks in advance for your help.
> > > > > Best,
> > > > 
> > > > 
> > > > I just retry to download the dataset from kaggle, on my side there is no problem downloading. Could you please provide more details of the errors you encountered?
> > > > To download the dataset correctly, you should press the download button on the top right shown in the screenshot below to ensure you download the whole dataset. ![image](https://private-user-images.githubusercontent.com/43100519/324059694-a11d9a0c-cd7b-4037-8274-36a72c40ad50.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3NTExNzIsIm5iZiI6MTcxMzc1MDg3MiwicGF0aCI6Ii80MzEwMDUxOS8zMjQwNTk2OTQtYTExZDlhMGMtY2Q3Yi00MDM3LTgyNzQtMzZhNzJjNDBhZDUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDAxNTQzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5NTRmZjJhZDQ5NTUwZGYxM2I4MWZmOWUxMjE2ZGZlNGQ0YWExNWJiZWUxZDE0NTE0NzU5YTc2M2E3YTk4NTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AaQqz9S1IZU-Cyxuoqmm5X--WDm8RSpdMCmwmmGFxXE)
> > > 
> > > 
> > > Hello, I am able to download the dataset from Kaggle without any issues. However, when I open the data:
> > > 
> > > * All the images appear as black images.
> > > * The annotation count for coconut_b is only 117,378.
> > > 
> > > Could you please check if there is a problem with these aspects? Thank you!
> > 
> > 
> > Thanks for checking the data.
> > 
> > 1. for the black images, they are panoptic masks with discrete continuous numbers required panopticapi for visualization.
> > 2. the split size for coconut-b, is actually the the extra split size subtract coconut-s, so I will update the script to merge the provided coconut-b and coconut-s to build the ready-to-use coconut-b in the paper. The other option will be directly upload the ready-to-use version. Sorry about that, I am working on this.
> 
> Thank you for your prompt response. All of my questions have been answered, so I will close this issue. Once again, thank you for creating the dataset.

Hi, I've just updated the dataset where COCONut-B is ready to use once you download from Kaggle, please check [this](https://www.kaggle.com/datasets/xueqingdeng/coconut/ ) out.  Please feel free to leave your questions here.
