### ISSUE TITLE
无法从 panseg 转换到 instance

### ISSUE THREAD

**Issue by pazifik-cyber** [bytedance/coconut_cvpr2024#12]
首先非常感谢你们的工作。

我使用下面的脚本转换panseg，但是出现了问题。

## annotaion下载：
`python download_coconut.py --split coconut_b`

## 图片下载
使用了表格里面 coconut_b 的images 的下载链接 http://images.cocodataset.org/zips/unlabeled2017.zip

## 转换panseg
`python create_instance_by_panseg.py  
--mask-dir  coconut_b 
--image-dir unlabeled2017/ 
--panseg-info coconut_b.json 
 --output ./coconut_b_instance`

## 出现错误：
`global loadsave.cpp:248 findDecoder imread_('unlabeled2017//000000000009.jpg'): can't open/read file: check file path/integrity`

请问是我下载的图片不对么？

**Comment by xdeng7** [comment]
> 首先非常感谢你们的工作。
> 
> 我使用下面的脚本转换panseg，但是出现了问题。
> 
> ## annotaion下载：
> `python download_coconut.py --split coconut_b`
> 
> ## 图片下载
> 使用了表格里面 coconut_b 的images 的下载链接 http://images.cocodataset.org/zips/unlabeled2017.zip
> 
> ## 转换panseg
> `python create_instance_by_panseg.py --mask-dir coconut_b --image-dir unlabeled2017/ --panseg-info coconut_b.json --output ./coconut_b_instance`
> 
> ## 出现错误：
> `global loadsave.cpp:248 findDecoder imread_('unlabeled2017//000000000009.jpg'): can't open/read file: check file path/integrity`
> 
> 请问是我下载的图片不对么？

'unlabeled2017//000000000009.jpg' 这个路径是哪里来的，怎么有两个斜杠

**Comment by pazifik-cyber** [comment]
> > 首先非常感谢你们的工作。
> > 我使用下面的脚本转换panseg，但是出现了问题。
> > ## annotaion下载：
> > `python download_coconut.py --split coconut_b`
> > ## 图片下载
> > 使用了表格里面 coconut_b 的images 的下载链接 http://images.cocodataset.org/zips/unlabeled2017.zip
> > ## 转换panseg
> > `python create_instance_by_panseg.py --mask-dir coconut_b --image-dir unlabeled2017/ --panseg-info coconut_b.json --output ./coconut_b_instance`
> > ## 出现错误：
> > `global loadsave.cpp:248 findDecoder imread_('unlabeled2017//000000000009.jpg'): can't open/read file: check file path/integrity`
> > 请问是我下载的图片不对么？
> 
> 'unlabeled2017//000000000009.jpg' 这个路径是哪里来的，怎么有两个斜杠

好像是因为 '--image-dir unlabeled2017/' 路径多了个 '/' 。
转换 coconut_b 是需要把 unlabeled2017  和 train2017 先合并才行吧？

**Comment by xdeng7** [comment]
> > > 首先非常感谢你们的工作。
> > > 我使用下面的脚本转换panseg，但是出现了问题。
> > > ## annotaion下载：
> > > `python download_coconut.py --split coconut_b`
> > > ## 图片下载
> > > 使用了表格里面 coconut_b 的images 的下载链接 http://images.cocodataset.org/zips/unlabeled2017.zip
> > > ## 转换panseg
> > > `python create_instance_by_panseg.py --mask-dir coconut_b --image-dir unlabeled2017/ --panseg-info coconut_b.json --output ./coconut_b_instance`
> > > ## 出现错误：
> > > `global loadsave.cpp:248 findDecoder imread_('unlabeled2017//000000000009.jpg'): can't open/read file: check file path/integrity`
> > > 请问是我下载的图片不对么？
> > 
> > 
> > 'unlabeled2017//000000000009.jpg' 这个路径是哪里来的，怎么有两个斜杠
> 
> 好像是因为 '--image-dir unlabeled2017/' 路径多了个 '/' 。 转换 coconut_b 是需要把 unlabeled2017 和 train2017 先合并才行吧？ 路径需要输入正确才行，coconut_b 是unlabel和train的合集，需要先合并到一起

**Comment by xdeng7** [comment]
> > > 首先非常感谢你们的工作。
> > > 我使用下面的脚本转换panseg，但是出现了问题。
> > > ## annotaion下载：
> > > `python download_coconut.py --split coconut_b`
> > > ## 图片下载
> > > 使用了表格里面 coconut_b 的images 的下载链接 http://images.cocodataset.org/zips/unlabeled2017.zip
> > > ## 转换panseg
> > > `python create_instance_by_panseg.py --mask-dir coconut_b --image-dir unlabeled2017/ --panseg-info coconut_b.json --output ./coconut_b_instance`
> > > ## 出现错误：
> > > `global loadsave.cpp:248 findDecoder imread_('unlabeled2017//000000000009.jpg'): can't open/read file: check file path/integrity`
> > > 请问是我下载的图片不对么？
> > 
> > 
> > 'unlabeled2017//000000000009.jpg' 这个路径是哪里来的，怎么有两个斜杠
> 
> 好像是因为 '--image-dir unlabeled2017/' 路径多了个 '/' 。 转换 coconut_b 是需要把 unlabeled2017 和 train2017 先合并才行吧？

请问这个问题解决了吗
