### ISSUE TITLE
Incorrect COCO validation annotation misses / errors. All merged into single mask.

### ISSUE THREAD

**Issue by miquel-espinosa** [bytedance/coconut_cvpr2024#16]
Hi. Thanks for the work.

First I convert to `coconut_instances_val.json` following the instructions from here: https://github.com/bytedance/coconut_cvpr2024/tree/main/tutorials/kmaxdeeplab_instance

Then, I try to use the generated `coconut_instances_val.json` file with the usual COCO validation, I am encountering a few annotation misses. This is, images that in the original COCO Val were annotated, but in COCONut Val are not!
This is problematic if we want to use COCONut for evalutation and comparison.

For example:
 - Image id: 360325
![image](https://github.com/bytedance/coconut_cvpr2024/assets/34089118/dd3c23a6-f8d3-4247-afc1-dde624fd30b8)

 - Image id: 329323 
![image](https://github.com/bytedance/coconut_cvpr2024/assets/34089118/92734231-715b-4e91-9373-2300bedd1008)

Let me know if you can reproduce the error.
I hope this can be solved soon.
Thanks!

**Comment by xdeng7** [comment]
> Hi. Thanks for the work.
> 
> First I convert to `coconut_instances_val.json` following the instructions from here: https://github.com/bytedance/coconut_cvpr2024/tree/main/tutorials/kmaxdeeplab_instance
> 
> Then, I try to use the generated `coconut_instances_val.json` file with the usual COCO validation, I am encountering a few annotation misses. This is, images that in the original COCO Val were annotated, but in COCONut Val are not! This is problematic if we want to use COCONut for evalutation and comparison.
> 
> For example:
> 
> * Image id: 360325
>   ![image](https://private-user-images.githubusercontent.com/34089118/337704842-dd3c23a6-f8d3-4247-afc1-dde624fd30b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwMDYzNTksIm5iZiI6MTcxODAwNjA1OSwicGF0aCI6Ii8zNDA4OTExOC8zMzc3MDQ4NDItZGQzYzIzYTYtZjhkMy00MjQ3LWFmYzEtZGRlNjI0ZmQzMGI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEwVDA3NTQxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExOWQ1OTA4NDI3NDhiMzNiY2M2ZWI5MTNiYTdmN2Q2ODM5Y2Y2NTgxYTllY2EzNDdiYmFhOTRjZjJlNjk4NTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lFOA9LelS-4qPaxv9zBmw3kZArp48RDp_aHmKP1YBCo)
> * Image id: 329323
>   ![image](https://private-user-images.githubusercontent.com/34089118/337705793-92734231-715b-4e91-9373-2300bedd1008.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwMDYzNTksIm5iZiI6MTcxODAwNjA1OSwicGF0aCI6Ii8zNDA4OTExOC8zMzc3MDU3OTMtOTI3MzQyMzEtNzE1Yi00ZTkxLTkzNzMtMjMwMGJlZGQxMDA4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEwVDA3NTQxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxYjZjYzkzYjJlM2JkNTY5Yzg2ZDlmNjFkOThjODRmODc0MjY0NGRjYjcxYTQxODYxOTY1NDZjOGFhYzcyNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.d6nOOJgfIFzFjJOsJzN_Mo8H0ZsyUZ_Ks0LhUtcYFkY)
> 
> Let me know if you can reproduce the error. I hope this can be solved soon. Thanks!

which tool are you using to visualize COCO and COCONut instance?

**Comment by miquel-espinosa** [comment]
@xdeng7
It's just the usual pycocotools, with the new generated json file.

```python
coco2=COCO(annFile2)
# put specific imgids you want to visualize
img_id_list2=[360325]
imgIds2 = coco2.getImgIds(imgIds = img_id_list2)
img2 = coco2.loadImgs(imgIds2[0])[0]
I2 = io.imread(img2['coco_url'])
# load and display instance annotations
plt.imshow(I2); plt.axis('off')
annIds2 = coco2.getAnnIds(imgIds=img2['id'],  iscrowd=1)
anns2 = coco2.loadAnns(annIds2)
coco2.showAnns(anns2)
```

**Comment by miquel-espinosa** [comment]
In particular, here are some image ids, so that you can too check:
- `329323`, `360325`,  `562197`, `128658`

**Comment by xdeng7** [comment]
> In particular, here are some image ids, so that you can too check:
> 
> * `329323`, `360325`,  `562197`, `128658`

thank you for the question. I think that's the problem of some of masks were identified as "crowd" regardless of the object size.  We will fix these image ids to separate the masks from "crowd" masks.
![img_v3_02bo_5072cfe6-de3a-48ce-a4ed-6e16b4c2e5dh](https://github.com/bytedance/coconut_cvpr2024/assets/43100519/f413ac33-98b6-4696-8c26-e02c2da237fc)

**Comment by miquel-espinosa** [comment]
Yes, that is exactly what it's happening. 
Let me know when it is solved, so I can rerun instance segmentation evaluation with the fixed COCONut.
Thanks a lot!

**Comment by xdeng7** [comment]
> Yes, that is exactly what it's happening. Let me know when it is solved, so I can rerun instance segmentation evaluation with the fixed COCONut. Thanks a lot!

yes, will make announcement when upload new version of the dataset.

**Comment by JohannesTheo** [comment]
Hey @miquel-espinosa this ist not a bug. These cowd annotations come from [sama-coco](https://www.sama.com/sama-coco-dataset). If I understand correctly, sama-coco is used as a starting point and its masks are refined to create the instances (things) in `relabeled_coco_val_panoptic.json`. Is this assumption @xdeng7 this correct? I'm a little surprised by your previous answer.

- `329323`, `360325`, `562197`, `128658`, `185157`

<img width="1249" alt="Screenshot 2024-08-22 at 12 19 23" src="https://github.com/user-attachments/assets/f9c99743-a9a0-4d7a-ad68-38a4bf986611">
<img width="1247" alt="Screenshot 2024-08-22 at 12 19 35" src="https://github.com/user-attachments/assets/92a1b1be-7b92-43c1-b17a-c86f7305d3f8">
<img width="1244" alt="Screenshot 2024-08-22 at 12 19 44" src="https://github.com/user-attachments/assets/cfb3ee1b-f89c-4f50-b62a-6c664f3cb96b">
<img width="1241" alt="Screenshot 2024-08-22 at 12 19 56" src="https://github.com/user-attachments/assets/a93eedee-e18e-4fe6-9cd7-83c5fdbf5643">
<img width="1246" alt="Screenshot 2024-08-22 at 12 20 06" src="https://github.com/user-attachments/assets/9bea83e8-97a7-4c05-9ff9-9fd6e145324d">
