### ISSUE TITLE
No such file or directory: 'datasets/coco/annotations/panoptic_val2017.json'

### ISSUE THREAD

**Issue by paulxiongfree** [bytedance/coconut_cvpr2024#17]
got this when trying to follow semantic segmentation toturial, couldn't find panoptic_val2017.json anywhere

**Comment by xdeng7** [comment]
> got this when trying to follow semantic segmentation toturial, couldn't find panoptic_val2017.json anywhere

you need to export the dataset path for detectron2 when using the convertion script. `export DETECTRON2_DATASETS=$YOUR DATASET_PATH`

**Comment by paulxiongfree** [comment]
I solved this issue by downloading annotation file at https://cocodataset.org/#download
