### ISSUE TITLE
COCONut-L annotations

### ISSUE THREAD

**Issue by spacycoder** [bytedance/coconut_cvpr2024#19]
Hi, great work! Where can I find the annotations for COCONut-L?

**Comment by ceinzx** [comment]
Yeah I have the same problem and also find the masksa of COCONut-L in Hugging Face is not right, the amount is 118k and files completely same as COCONut-S. Why...

**Comment by xdeng7** [comment]
> Yeah I have the same problem and also find the masks of COCONut-L in Hugging Face are not right, the amount is 118k and files completely same as COCONut-S. Why...

sorry for uploading the wrong files, now they are fixed.
