### ISSUE TITLE
some annotations miss

### ISSUE THREAD

**Issue by Tim5Tang** [bytedance/coconut_cvpr2024#2]
a good job, but some annos miss,  i have download the version 9 from the kaggle
for example, the image id 000000272411 miss the person
![1713926133320](https://github.com/bytedance/coconut_cvpr2024/assets/9462119/3db34f46-bd55-4794-9f53-56e61225eba5)
you can print the info from json for check
{'category_id': 199, 'iscrowd': 0, 'isthing': 0, 'image_id': 272411, 'area': 47638, 'bbox': [0.0, 6.0, 444.0, 222.0]}
{'category_id': 138, 'iscrowd': 0, 'isthing': 0, 'image_id': 272411, 'area': 44094, 'bbox': [0.0, 508.0, 444.0, 132.0]}
{'category_id': 185, 'iscrowd': 0, 'isthing': 0, 'image_id': 272411, 'area': 8111, 'bbox': [22.0, 253.0, 422.0, 289.0]}
{'category_id': 43, 'isthing': 1, 'iscrowd': 0, 'image_id': 272411, 'area': 11328, 'bbox': [240.0, 387.0, 164.0, 159.0]}

**Comment by xdeng7** [comment]
> a good job, but some annos miss, i have download the version 9 from the kaggle for example, the image id 000000272411 miss the person ![1713926133320](https://private-user-images.githubusercontent.com/9462119/325055335-3db34f46-bd55-4794-9f53-56e61225eba5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NDMzNjYsIm5iZiI6MTcxMzk0MzA2NiwicGF0aCI6Ii85NDYyMTE5LzMyNTA1NTMzNS0zZGIzNGY0Ni1iZDU1LTQ3OTQtOWY1My01NmU2MTIyNWViYTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjRUMDcxNzQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2NlYmQyNGEzNWY5MThkMzBjOTBkY2FjMTc0MjdiNWE1NzliMjQ2ZDk1MmI1MTliZmI0MjBhOTM3NzY1ODVkYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.CL-jg1itbh4ONKflpyCVUYwXtLd4b2doa1VHzDN914I) you can print the info from json for check {'category_id': 199, 'iscrowd': 0, 'isthing': 0, 'image_id': 272411, 'area': 47638, 'bbox': [0.0, 6.0, 444.0, 222.0]} {'category_id': 138, 'iscrowd': 0, 'isthing': 0, 'image_id': 272411, 'area': 44094, 'bbox': [0.0, 508.0, 444.0, 132.0]} {'category_id': 185, 'iscrowd': 0, 'isthing': 0, 'image_id': 272411, 'area': 8111, 'bbox': [22.0, 253.0, 422.0, 289.0]} {'category_id': 43, 'isthing': 1, 'iscrowd': 0, 'image_id': 272411, 'area': 11328, 'bbox': [240.0, 387.0, 164.0, 159.0]}

thanks for catching this problem, such noise of annotation do exist. If you go to check our paper, our expert rater will sample 50% from the annotations queues to check if all the masks meet expectation. But our raters should do 100% final check on COCO-val set (5000 images). If this id is in val set, could you please provide the image id, so that we could fix it really quick.

**Comment by Tim5Tang** [comment]
thanks ...
