### ISSUE TITLE
object365_patch_ids.txt' seems to be missing 

### ISSUE THREAD

**Issue by tuliti** [bytedance/coconut_cvpr2024#23]
The tutorial` kmaxdeeplab_panoptic` refers to a file `object365_patch_ids.txt`, which seems to be missing. 

Could you share the file so that people do not have to download the whole 365 dataset? 

Thank you in advance.

**Comment by xdeng7** [comment]
> The tutorial` kmaxdeeplab_panoptic` refers to a file `object365_patch_ids.txt`, which seems to be missing.
> 
> Could you share the file so that people do not have to download the whole 365 dataset?
> 
> Thank you in advance.

The full patch ids are 25,32,35,40, thanks for the advice, I should upload the images to google drive soon.
