### ISSUE TITLE
coconut_val size and composition

### ISSUE THREAD

**Issue by tuliti** [bytedance/coconut_cvpr2024#24]
First off, overall really nice work!

We are currently trying to work with coconut_val.

Is there any material (relevant patches of objects 365, script)  on how to generate coconut val? 

It seems that different versions of jsons for coconut val exist.
- https://huggingface.co/datasets/xdeng77/coconut_val
-> length of roughly 20k 
- coconut_val_panoptic.json 
-> ~25k images

Thank you very much for your help.

**Comment by tuliti** [comment]
**Further insights:**
`coconut_val_panoptic.json`
- contains in total 25,505 images
-- 4,996 images with a coco url
-- 20,509 images without a coco url

Overall matching the paper description:
_...along with an additional 20K images from Objects365 dataset..._


**Objects 365 data:**
Loading all three jsons (train test val) from Objects 365 we get uniques images of 

- total (combined): 2,015,880
- train: 1,742,292
- val: 80,000
- test: 193,588

Json names: 
- zhiyuan_objv2_train.json
- zhiyuan_objv2_val.json
- zhiyuan_objv2_test.json

Matching over the "id" for each image, we are left with 
- 15,803 coconut_val image_ids present in the object_365 jsons
-  **4,706 coconut_val image_ids unable to match to the object_365 jsons** 

Are all the 20k coconut_val images from the objects 365 versions that is available? 
maybe there is another matching that I might have missed or a newer v3 version might exist.

**Comment by xdeng7** [comment]
> **Further insights:** `coconut_val_panoptic.json`
> 
> * contains in total 25,505 images
>   -- 4,996 images with a coco url
>   -- 20,509 images without a coco url
> 
> Overall matching the paper description: _...along with an additional 20K images from Objects365 dataset..._
> 
> **Objects 365 data:** Loading all three jsons (train test val) from Objects 365 we get uniques images of
> 
> * total (combined): 2,015,880
> * train: 1,742,292
> * val: 80,000
> * test: 193,588
> 
> Json names:
> 
> * zhiyuan_objv2_train.json
> * zhiyuan_objv2_val.json
> * zhiyuan_objv2_test.json
> 
> Matching over the "id" for each image, we are left with
> 
> * 15,803 coconut_val image_ids present in the object_365 jsons
> * **4,706 coconut_val image_ids unable to match to the object_365 jsons**
> 
> Are all the 20k coconut_val images from the objects 365 versions that is available? maybe there is another matching that I might have missed or a newer v3 version might exist.

yes, I upload the images to google drive and update the tutorial, please check the tutorial to use it.
