### ISSUE TITLE
object365_train_panseg is error

### ISSUE THREAD

**Issue by feivellau** [bytedance/coconut_cvpr2024#25]
Many files in the folder are corrupted and they are 0 kb

**Comment by xdeng7** [comment]
> Many files in the folder are corrupted and they are 0 kb

we annotate extra 60k images from objects365 for coconut-large, I should remove these links soon to update the files. thanks for the issue.

**Comment by xdeng7** [comment]
please check  the updated files in huggingface, kaggle should be updated soon. And please follow [preparing_dataset](https://github.com/bytedance/coconut_cvpr2024/blob/main/preparing_datasets.md) to use it.
