### ISSUE TITLE
Most annotations missing for COCONut-L in Huggingface and Kaggle!

### ISSUE THREAD

**Issue by tommiekerssies** [bytedance/coconut_cvpr2024#26]
In the Huggingface version of COCONut-L the majority of the files is a symlink to a directory that is not shared.
In the Kaggle version of COCONut-L the majority of the files is 0 bytes.

**Comment by tommiekerssies** [comment]
Thank you, much appreciated!

**Comment by xdeng7** [comment]
remove the invalid file links, all the panoptic masks are available now. also please check the tutorial to use it.
