### ISSUE TITLE
May I ask when it will be released COCONut-val，COCONut-L and instance segmentation annotations (no need to convert from the panoptic masks)?

### ISSUE THREAD

**Issue by longtaojiang** [bytedance/coconut_cvpr2024#28]
May I ask when the author will release COCONut-val，COCONut-L and instance segmentation annotations (no need to convert from the panoptic masks) ? 

I hope the author can release these datasets as soon as possible. I have some ideas that have been preliminarily validated and proven effective. I need the high-quality dataset of this article to advance my work, so that I can submit and cite this dataset as much as possible at the computer vision summit at the end or beginning of the year.

**Comment by longtaojiang** [comment]
Oh, it seems like these datasets have already been released, they just need to be downloaded and converted

**Comment by MartaTintore** [comment]
Hey @longtaojiang I can only see the instance segmentation annotations from COCONut-S and the relabeled COCO-val, any change you could find them for the remaining sets (COCONut-B/L and COCONut-val)? Thanks, I am also very interested in using this dataset in my research :)

**Comment by xdeng7** [comment]
> Hey @longtaojiang I can only see the instance segmentation annotations from COCONut-S and the relabeled COCO-val, any change you could find them for the remaining sets (COCONut-B/L and COCONut-val)? Thanks, I am also very interested in using this dataset in my research :)

thanks for the issue, I should release them soon estimated by this Wednesday PST.

**Comment by MartaTintore** [comment]
Great, thanks!

**Comment by xdeng7** [comment]
> Hey @longtaojiang I can only see the instance segmentation annotations from COCONut-S and the relabeled COCO-val, any change you could find them for the remaining sets (COCONut-B/L and COCONut-val)? Thanks, I am also very interested in using this dataset in my research :)

please check this [gdrive](https://drive.google.com/file/d/12MM0R25FO1pkuN76dHyTj7O4TwUOYZ47/view?usp=drive_link) link for the instance masks.
