### ISSUE TITLE
Where can I find the remaining 50k dataset in COCONut-L?

### ISSUE THREAD

**Issue by longtaojiang** [bytedance/coconut_cvpr2024#29]
Thank you for this outstanding work.
I have noticed that the number of annotations released by COCONut-L currently includes COCO trains, COCO unlabelled，60k objects365， Roughly around 300k, but declared as 358k in the paper and github?

**Comment by longtaojiang** [comment]
At the same time, I found that the images in object365_train_cnseg.tar https://huggingface.co/datasets/xdeng77/coconut_large/tree/main
do not correspond to the subset of images you provided for objects365 https://drive.google.com/drive/folders/1ZumOrkikulK96MbBxayO07JP_HV-fgTW

**Comment by xdeng7** [comment]
now it is available at huggingface, should update kaggle soon.
