### ISSUE TITLE
where is the annotation?

### ISSUE THREAD

**Issue by z-jiaming** [bytedance/coconut_cvpr2024#3]
Thanks for your good work!

I can`t find the segmentation annotations in your files.

For each anno in 'annotations', instances_train2017.json of COCO provides them like:
<img width="490" alt="Snipaste_2024-04-25_17-06-53" src="https://github.com/bytedance/coconut_cvpr2024/assets/42411674/47e1ea45-3a13-4d72-989b-77bac909c5f7">

But it doesn't seem to be the same in your file.
<img width="455" alt="image" src="https://github.com/bytedance/coconut_cvpr2024/assets/42411674/4d0c0ea2-d4f5-4aad-b72e-2f3a506c466b">

Do I use the wrong way?

**Comment by z-jiaming** [comment]
Thus, I can not use pycocotools.coco.COCO directly.

<img width="742" alt="image" src="https://github.com/bytedance/coconut_cvpr2024/assets/42411674/a90e9d06-32df-4006-8a94-5555b4fa0595">

**Comment by xdeng7** [comment]
> Thus, I can not use pycocotools.coco.COCO directly.
> 
> <img alt="image" width="742" src="https://private-user-images.githubusercontent.com/42411674/325548993-a90e9d06-32df-4006-8a94-5555b4fa0595.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwNjY5MzQsIm5iZiI6MTcxNDA2NjYzNCwicGF0aCI6Ii80MjQxMTY3NC8zMjU1NDg5OTMtYTkwZTlkMDYtMzJkZi00MDA2LThhOTQtNTU1NWI0ZmEwNTk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI1VDE3MzcxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkYWRlMDVhYzkzYjE1Y2MxYTYwNjc1MDNiMjgzMWNkMzRhZTBmN2E0MjhlNzg0ZjM4MzlhNjZhYmU4MGEzNTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zTvglnwgKDgWc4WVSMZjKut-BR7lzmTh3VJhd_837LQ">

we only provide the panoptic mask in the download link, it looks like you are using instance masks with pycocotools, we recommend you to follow the tutorial under the folder "kmaxdeeplab_instance" in this repo to convert the panoptic masks to instance masks. The tool will just ignore the "stuff" masks but generate "thing" instance masks that will can be used in pycocotools.

**Comment by z-jiaming** [comment]
Thanks a lot for your reply!
I try to use the tool but find some bugs. I fix it, you can see the changes in https://github.com/bytedance/coconut_cvpr2024/pull/4
