### ISSUE TITLE
Annotation JSON files missing for COCONut-L

### ISSUE THREAD

**Issue by tommiekerssies** [bytedance/coconut_cvpr2024#30]
There are no annotation JSON files for COCONut-L (objects 365) in kaggle or huggingface. Only the png's.

**Comment by xdeng7** [comment]
> There are no annotation JSON files for COCONut-L (objects 365) in kaggle or huggingface. Only the png's.

uploaded to huggingface, please check

**Comment by MartaTintore** [comment]
I also cant see the L version... Any plan to release them soon?

**Comment by xdeng7** [comment]
> I also cant see the L version... Any plan to release them soon?

Could you please check the [huggingface](https://huggingface.co/datasets/xdeng77/coconut_large)  for the panoptic masks and our [google drive](https://drive.google.com/drive/folders/1KPeJ1qdrNGfyTifQYiuYutElAqXcQ9nq?usp=sharing) the converted instance masks ?

**Comment by xdeng7** [comment]
COCONut-Large has been updated please check the [huggingface](https://huggingface.co/datasets/xdeng77/coconut_large) for the panoptic masks and our [google drive](https://drive.google.com/drive/folders/1KPeJ1qdrNGfyTifQYiuYutElAqXcQ9nq?usp=sharing) the converted instance masks.
