### ISSUE TITLE
COCONut-B Image Download Link only has 118k images

### ISSUE THREAD

**Issue by NickHerrig** [bytedance/coconut_cvpr2024#8]
The COCONut-B image download link downloads a zip file with only 118k images instead of the documented 241k images.

I noticed that the provided annotations have 241690 masks, however when downloading the image link there are only 120k images. 

I'm using the link in the provided markdown below:
![image](https://github.com/bytedance/coconut_cvpr2024/assets/33797354/782ea402-1e70-4ad4-b6aa-667dac7dfcd7)

Should I expect to see the full 242k Images in this image download link?

Or is the idea that COCONut-B = Train2017 + Unlabeled2017 + Val2017

**Comment by NickHerrig** [comment]
Never mind, should have read the paper. 

![image](https://github.com/bytedance/coconut_cvpr2024/assets/33797354/9ee0c8a4-adf1-4680-8c30-abf49cef5414)

Closing this

**Comment by xdeng7** [comment]
> Never mind, should have read the paper.
> 
> ![image](https://private-user-images.githubusercontent.com/33797354/326549325-9ee0c8a4-adf1-4680-8c30-abf49cef5414.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0MTYzNDIsIm5iZiI6MTcxNDQxNjA0MiwicGF0aCI6Ii8zMzc5NzM1NC8zMjY1NDkzMjUtOWVlMGM4YTQtYWRmMS00NjgwLThjMzAtYWJmNDljZWY1NDE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDE4NDA0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiMDdkZmViODgyYWY4MzViNDlhZjY2M2IwZmY2NDEzZTI1M2YzMGE2ZGYxZTFhNmEwZWYxYjU4NjUzOGNlNGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0c_I3vL7ejvo248ix-VeZ7XX6yTa0Ttshbx5Mh8n64Y)
> 
> Closing this

The previous link on kaggle for coconut-B only contains the extra split from unlabeled set and will need one more step to merge the files. But last week I already update the kaggle link to version 9 which contains the full set of coconut-B and no extra merging steps are needed.  This updated version should contain 242k masks.
<img width="1249" alt="image" src="https://github.com/bytedance/coconut_cvpr2024/assets/43100519/5b1b8b93-98a4-4fd1-a89b-2668b7f76e08">
