### ISSUE TITLE
Panseg to Instance Segmentation Script Produces Inaccurate Annotations when objects overlap

### ISSUE THREAD

**Issue by NickHerrig** [bytedance/coconut_cvpr2024#9]
I'm using the script to transform the panseg annotations to instance segmentation and am seeing undesirable annotations. 

https://github.com/bytedance/coconut_cvpr2024/blob/main/tutorials/kmaxdeeplab_instance/create_instance_by_panseg.py

Here is example image 000000004134.jpg from the val2017 dataset, specifically  the dining table class overlapping the person. 

![image](https://github.com/bytedance/coconut_cvpr2024/assets/33797354/da81630a-bdc2-4428-956c-3eacf049a784).

Here is another example image 000000025139.jpg from the val2017 dataset where the zebra segmentation appear off. 
<img width="1512" alt="image" src="https://github.com/bytedance/coconut_cvpr2024/assets/33797354/c342f129-ed4f-409e-8c9f-32b3ee8f7c24">

It looks like the script was recently updated, do you know what could be causing this?

**Comment by NickHerrig** [comment]
For example, here are the masks for the zebra instance, So i expected them to align more closely. 
Please ignore my class labels, as I purposefully didn't provide these

<img width="515" alt="image" src="https://github.com/bytedance/coconut_cvpr2024/assets/33797354/3a8b7643-024b-44c4-9ff7-8885ab74c9fd">

**Comment by xdeng7** [comment]
> I'm using the script to transform the panseg annotations to instance segmentation and am seeing undesirable annotations.
> 
> https://github.com/bytedance/coconut_cvpr2024/blob/main/tutorials/kmaxdeeplab_instance/create_instance_by_panseg.py
> 
> Here is example image 000000004134.jpg from the val2017 dataset, specifically the dining table class overlapping the person.
> 
> ![image](https://private-user-images.githubusercontent.com/33797354/326625781-da81630a-bdc2-4428-956c-3eacf049a784.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ1MDIwMjYsIm5iZiI6MTcxNDUwMTcyNiwicGF0aCI6Ii8zMzc5NzM1NC8zMjY2MjU3ODEtZGE4MTYzMGEtYmRjMi00NDI4LTk1NmMtM2VhY2YwNDlhNzg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDMwVDE4Mjg0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhMDdlN2QxNTNjMGQxMmMyNjE4OWQyZjlhNDY4MDhiMGU4YWJhMDBmNTk5MDcyOWQ0NzFlMGFkOWUwOGRjMTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.t4gnDEvXvinbPfsOmg9TlI4-ARH9jFA8hvyNlp-mpiw).
> 
> Here is another example image 000000025139.jpg from the val2017 dataset where the zebra segmentation appear off. <img alt="image" width="1512" src="https://private-user-images.githubusercontent.com/33797354/326626663-c342f129-ed4f-409e-8c9f-32b3ee8f7c24.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ1MDIwMjYsIm5iZiI6MTcxNDUwMTcyNiwicGF0aCI6Ii8zMzc5NzM1NC8zMjY2MjY2NjMtYzM0MmYxMjktZWQ0Zi00MDllLThjOWYtMzJiM2VlOGY3YzI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDMwVDE4Mjg0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3MDJkNmEyNGE3M2U4Y2MyZGI2ZTNjMTc1MTkwOGU0MmRlM2M2MmZlOGM0OTQ1MzNlNjVlYWVhOGYyMThkMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bg0QwR7BHSXKyR9fmv0yUFwTfMVGUc2QYz0eXUKdrvg">
> 
> It looks like the script was recently updated, do you know what could be causing this?

hi, thanks for the question. I believe this could be the problem of how you open the instance mask. I used pycocotools api, it looks good on my side. You can check my recent commit on the visualization:  https://github.com/bytedance/coconut_cvpr2024/blob/main/tutorials/kmaxdeeplab_instance/vis_converted_instance.ipynb

attach my visualization results below:
![image](https://github.com/bytedance/coconut_cvpr2024/assets/43100519/932cf78d-8971-4057-b7ef-d8f73da52f59)

**Comment by xdeng7** [comment]
> For example, here are the masks for the zebra instance, So i expected them to align more closely. Please ignore my class labels, as I purposefully didn't provide these
> 
> <img alt="image" width="515" src="https://private-user-images.githubusercontent.com/33797354/326628527-3a8b7643-024b-44c4-9ff7-8885ab74c9fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ1MDI0NTMsIm5iZiI6MTcxNDUwMjE1MywicGF0aCI6Ii8zMzc5NzM1NC8zMjY2Mjg1MjctM2E4Yjc2NDMtMDI0Yi00NGM0LTlmZjctODg4NWFiNzRjOWZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDMwVDE4MzU1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlZWIzZDljOTM5Y2U2ZjJiYWZiY2U5ZDdhNGM0NTFiNTgwNTEyYzQzNWNkZDhkMzUxMGJmMGE0MjhmMDViNDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iyTbDtf5BArnBXxnLxD-itbB2kp8X_GfhFew9LU0pw4">

for the zebra, the instance mask should be good as in my visualization.
![image](https://github.com/bytedance/coconut_cvpr2024/assets/43100519/a1b3cf8c-0b5f-4b1a-8d90-644e7a864d3b)

**Comment by NickHerrig** [comment]
Thank you, I also recreated this with CV2 and just drawing the polygon segments. 
I appreciate you looking at this. Closing now.
